/* Generated by tools/legal/build.py from the redline specifications. Do not edit by hand.
   Draft legal texts (2 Oct 2026), pending review by the firm's attorney. */
window.CREDO_LEGAL = {
 "terms": {
  "title": "Terms of Use",
  "blocks": [
   {
    "t": "h1",
    "x": "Terms of Use"
   },
   {
    "t": "p",
    "x": "Last updated: [date of publication]"
   },
   {
    "t": "p",
    "x": "This website is attorney advertising. It is for informational purposes only, does not constitute legal advice and may not reflect the most current legal developments. Use of this website does not create an attorney-client relationship; only a written engagement agreement signed by you and the firm can establish an attorney-client relationship. Credo Legal and all contributing authors expressly disclaim all liability to any person with respect to the contents of this website. Imagery used on this website utilizes fictionalized events or scenes with participation of models."
   },
   {
    "t": "h2",
    "x": "These Terms govern"
   },
   {
    "t": "p",
    "x": "the use of this Website, and, any other related Agreement or legal relationship with the Owner in a legally binding way. In these Terms, \"Credo Legal\", \"the Owner\", \"we\" and \"us\" mean the law firm named below; \"this Website\" means the firm's websites and landing pages on which these Terms appear; \"the Service\" means the information and the contact features (form, chat and phone) offered on this Website; \"User\" and \"you\" mean the person using this Website."
   },
   {
    "t": "p",
    "x": "The User must read this document carefully."
   },
   {
    "t": "p",
    "x": "This Website is provided by: Credo Legal – 1 Liberty Plaza, Suite 401, New York, NY 10006 [confirm legal entity name and address]"
   },
   {
    "t": "p",
    "x": "Mailing Address P.O. Box 105562, Atlanta, GA 30348-5562"
   },
   {
    "t": "p",
    "x": "Owner contact email: support@credolegal.com"
   },
   {
    "t": "h2",
    "x": "Attorney advertising"
   },
   {
    "t": "p",
    "x": "This Website is attorney advertising. Prior results do not guarantee a similar outcome. Credo Legal is a law firm. It is not a debt-settlement company and not a credit-counseling service."
   },
   {
    "t": "h2",
    "x": "No legal advice and no attorney-client relationship"
   },
   {
    "t": "p",
    "x": "Nothing on this Website is legal advice for your situation. Sending us a form, chatting with us, calling us or emailing us does not make you a client of the firm. You become a client only when you and the firm sign a written engagement agreement."
   },
   {
    "t": "p",
    "x": "Until then, we do not represent you and we are not keeping track of any deadline in your matter. If you have been served with a lawsuit or have a court date, do not wait for a reply from us: respond to the court by the deadline or speak to an attorney right away."
   },
   {
    "t": "p",
    "x": "Please do not send us confidential or sensitive information beyond what the form asks for, such as account numbers or Social Security numbers."
   },
   {
    "t": "h2",
    "x": "Where we provide services"
   },
   {
    "t": "p",
    "x": "Legal services are provided by attorneys licensed in the states the firm serves. We currently do not serve residents of the District of Columbia, Delaware, Idaho, North Carolina, Oklahoma, West Virginia or Wyoming. This list can change. This Website is not a solicitation in any jurisdiction where it would not comply with the rules that apply there."
   },
   {
    "t": "h2",
    "x": "Results, reviews and figures"
   },
   {
    "t": "p",
    "x": "Every matter is different. Statements about past results, client reviews, ratings and figures shown on this Website describe past matters. They are not a prediction or a guarantee of the outcome of your matter."
   },
   {
    "t": "p",
    "x": "Amounts set by law that are mentioned on this Website, such as statutory damages of up to $1,000 under the Fair Debt Collection Practices Act, are the most a court may award. They are not a promise that you will receive that amount."
   },
   {
    "t": "h2",
    "x": "How we may contact you"
   },
   {
    "t": "p",
    "x": "When you send us a form, start a chat or call us, you are asking us to respond. We may contact you by phone, text message and email at the contact details you gave us, about your inquiry."
   },
   {
    "t": "p",
    "x": "We send marketing calls or text messages made with automated technology only if you agreed to them where you gave us your number. Message and data rates may apply. You can reply STOP to a text message at any time to stop further texts. Agreeing to be contacted is not a condition of receiving any service."
   },
   {
    "t": "h2",
    "x": "Terms of use"
   },
   {
    "t": "p",
    "x": "Unless otherwise specified, the terms of use detailed in this section apply generally when using this Website. Single or additional conditions of use or access may apply in specific scenarios and in such cases are additionally indicated within this document."
   },
   {
    "t": "h2",
    "x": "By using this Website, Users confirm to meet the following requirements:"
   },
   {
    "t": "p",
    "x": "Users are at least 18 years old; Users live in the United States; Users aren’t located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist-supporting” country; Users aren’t listed on any U.S. Government list of prohibited or restricted parties;"
   },
   {
    "t": "h2",
    "x": "Content on this Website"
   },
   {
    "t": "p",
    "x": "Unless where otherwise specified or clearly recognizable, all content available on this Website is owned or provided by the Owner or its licensors."
   },
   {
    "t": "p",
    "x": "The Owner undertakes its utmost effort to ensure that the content provided on this Website infringes no applicable legal provisions or third-party rights. However, it may not always be possible to achieve such a result."
   },
   {
    "t": "p",
    "x": "In such cases, without prejudice to any legal prerogatives of Users to enforce their rights, Users are kindly asked to report related complaints using the contact details provided in this document."
   },
   {
    "t": "h2",
    "x": "Rights regarding content on this Website – All rights reserved"
   },
   {
    "t": "p",
    "x": "The Owner holds and reserves all intellectual property rights for any such content."
   },
   {
    "t": "p",
    "x": "Users may not therefore use such content in any way that is not necessary or implicit in the proper use of the Service."
   },
   {
    "t": "p",
    "x": "In particular, but without limitation, Users may not copy, download, share (beyond the limits set forth below), modify, translate, transform, publish, transmit, sell, sublicense, edit, transfer/assign to third parties or create derivative works from the content available on this Website, nor allow any third party to do so through the User or their device, even without the User’s knowledge."
   },
   {
    "t": "p",
    "x": "Where explicitly stated on this Website, the User may download, copy and/or share some content available through this Website for its sole personal and non-commercial use and provided that the copyright attributions and all the other attributions requested by the Owner are correctly implemented."
   },
   {
    "t": "p",
    "x": "Any applicable statutory limitation or exception to copyright shall stay unaffected."
   },
   {
    "t": "h2",
    "x": "Information you send us"
   },
   {
    "t": "p",
    "x": "When you send us information through a form, the chat or by phone or email, you confirm that it is accurate and that you are allowed to share it. We handle it as described in our Privacy Policy."
   },
   {
    "t": "h2",
    "x": "Access to external resources"
   },
   {
    "t": "p",
    "x": "Through this Website Users may have access to external resources provided by third parties. Users acknowledge and accept that the Owner has no control over such resources and is therefore not responsible for their content and availability."
   },
   {
    "t": "p",
    "x": "Conditions applicable to any resources provided by third parties, including those applicable to any possible grant of rights in content, result from each such third party’s terms and conditions or, in the absence of those, applicable statutory law."
   },
   {
    "t": "h2",
    "x": "Acceptable use"
   },
   {
    "t": "p",
    "x": "This Website and the Service may only be used within the scope of what they are provided for, under these Terms and applicable law."
   },
   {
    "t": "p",
    "x": "Users are solely responsible for making sure that their use of this Website and/or the Service violates no applicable law, regulations or third-party rights."
   },
   {
    "t": "p",
    "x": "Therefore, the Owner reserves the right to take any appropriate measure to protect its legitimate interests including by denying Users access to this Website or the Service, terminating contracts, reporting any misconduct performed through this Website or the Service to the competent authorities – such as judicial or administrative authorities – whenever Users engage or are suspected to engage in any of the following activities:"
   },
   {
    "t": "li",
    "x": "violate laws, regulations and/or these Terms;"
   },
   {
    "t": "li",
    "x": "infringe any third-party rights;"
   },
   {
    "t": "li",
    "x": "considerably impair the Owner’s legitimate interests;"
   },
   {
    "t": "li",
    "x": "offend the Owner or any third party."
   },
   {
    "t": "h2",
    "x": "Fees and engagement"
   },
   {
    "t": "p",
    "x": "Nothing is sold through this Website. The first consultation is free. Legal services are provided only under a written engagement agreement between you and the firm, which sets out the services and the fees. If these Terms and an engagement agreement say different things, the engagement agreement applies."
   },
   {
    "t": "h2",
    "x": "Liability and indemnification"
   },
   {
    "t": "h3",
    "x": "Disclaimer of Warranties"
   },
   {
    "t": "p",
    "x": "This Website is provided strictly on an “as is” and “as available” basis. Use of the Service is at Users’ own risk. To the maximum extent permitted by applicable law, the Owner expressly disclaims all conditions, representations, and warranties — whether express, implied, statutory or otherwise, including, but not limited to, any implied warranty of merchantability, fitness for a particular purpose, or non-infringement of third-party rights. No advice or information, whether oral or written, obtained by user from owner or through the Service will create any warranty not expressly stated herein."
   },
   {
    "t": "p",
    "x": "Without limiting the foregoing, the Owner, its subsidiaries, affiliates, licensors, officers, directors, agents, co-branders, partners, suppliers and employees do not warrant that the content is accurate, reliable or correct; that the Service will meet Users’ requirements; that the Service will be available at any particular time or location, uninterrupted or secure; that any defects or errors will be corrected; or that the Service is free of viruses or other harmful components. Any content downloaded or otherwise obtained through the use of the Service is downloaded at users own risk and users shall be solely responsible for any damage to Users’ computer system or mobile device or loss of data that results from such download or Users’ use of the Service."
   },
   {
    "t": "p",
    "x": "The Owner does not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by a third party through the Service or any hyperlinked website or service, and the Owner shall not be a party to or in any way monitor any transaction between Users and third-party providers of products or services."
   },
   {
    "t": "p",
    "x": "The Service may become inaccessible or it may not function properly with Users’ web browser, mobile device, and/or operating system. The owner cannot be held liable for any perceived or actual damages arising from Service content, operation, or use of this Service."
   },
   {
    "t": "p",
    "x": "Federal law, some states, and other jurisdictions, do not allow the exclusion and limitations of certain implied warranties. The above exclusions may not apply to Users. This Agreement gives Users specific legal rights, and Users may also have other rights which vary from state to state. The disclaimers and exclusions under this agreement shall not apply to the extent prohibited by applicable law."
   },
   {
    "t": "h3",
    "x": "Limitations of liability"
   },
   {
    "t": "p",
    "x": "To the maximum extent permitted by applicable law, in no event shall the Owner, and its subsidiaries, affiliates, officers, directors, agents, co-branders, partners, suppliers and employees be liable for"
   },
   {
    "t": "p",
    "x": "any indirect, punitive, incidental, special, consequential or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data or other intangible losses, arising out of or relating to the use of, or inability to use, the Service; and any damage, loss or injury resulting from hacking, tampering or other unauthorized access or use of the Service or User account or the information contained therein; any errors, mistakes, or inaccuracies of content; personal injury or property damage, of any nature whatsoever, resulting from User access to or use of the Service; any unauthorized access to or use of the Owner’s secure servers and/or any and all personal information stored therein; any interruption or cessation of transmission to or from the Service; any bugs, viruses, trojan horses, or the like that may be transmitted to or through the Service;"
   },
   {
    "t": "p",
    "x": "any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available through the Service; and/or the defamatory, offensive, or illegal conduct of any User or third party."
   },
   {
    "t": "p",
    "x": "This limitation of liability section shall apply to the fullest extent permitted by law in the applicable jurisdiction whether the alleged liability is based on contract, tort, negligence, strict liability, or any other basis, even if company has been advised of the possibility of such damage."
   },
   {
    "t": "p",
    "x": "Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, therefore the above limitations or exclusions may not apply to User. The terms give User specific legal rights, and User may also have other rights which vary from jurisdiction to jurisdiction. The disclaimers, exclusions, and limitations of liability under the terms shall not apply to the extent prohibited by applicable law."
   },
   {
    "t": "p",
    "x": "This section is about your use of this Website. It does not limit any duty the firm owes to its clients under an engagement agreement or under the rules of professional conduct."
   },
   {
    "t": "h3",
    "x": "Indemnification"
   },
   {
    "t": "p",
    "x": "The User agrees to defend, indemnify and hold the Owner and its subsidiaries, affiliates, officers, directors, agents, co-branders, partners, suppliers and employees harmless from and against any and all claims or demands, damages, obligations, losses, liabilities, costs or debt, and expenses, including, but not limited to, legal fees and expenses, arising from:"
   },
   {
    "t": "li",
    "x": "Users use of and access to the Service, including any data or content transmitted or received by User;"
   },
   {
    "t": "li",
    "x": "Users violation of these Terms, including, but not limited to, Users breach of any of the representations and warranties set forth in these Terms;"
   },
   {
    "t": "li",
    "x": "Users violation of any third-party rights, including, but not limited to, any right of privacy or intellectual property rights;"
   },
   {
    "t": "li",
    "x": "Users violation of any statutory law, rule, or regulation;"
   },
   {
    "t": "li",
    "x": "Users willful misconduct; or"
   },
   {
    "t": "h2",
    "x": "Common provisions"
   },
   {
    "t": "h3",
    "x": "No Waiver"
   },
   {
    "t": "p",
    "x": "The Owner’s failure to assert any right or provision under these Terms shall not constitute a waiver of any such right or provision. No waiver shall be considered a further or continuing waiver of such term or any other term."
   },
   {
    "t": "h3",
    "x": "Service interruption"
   },
   {
    "t": "p",
    "x": "To ensure the best possible service level, the Owner reserves the right to interrupt the Service for maintenance, system updates or any other changes, informing the Users appropriately."
   },
   {
    "t": "p",
    "x": "Within the limits of law, the Owner may also decide to suspend or terminate the Service altogether. If the Service is terminated, the Owner will cooperate with Users to enable them to withdraw Personal Data or information in accordance with applicable law."
   },
   {
    "t": "p",
    "x": "Additionally, the Service might not be available due to reasons outside the Owner’s reasonable control, such as “force majeure” (eg. labor actions, infrastructural breakdowns or blackouts etc)."
   },
   {
    "t": "h2",
    "x": "Privacy and cookies"
   },
   {
    "t": "p",
    "x": "To learn more about the use of their Personal Data, Users may refer to the Privacy Policy and the Cookie Policy of this Website."
   },
   {
    "t": "h3",
    "x": "Intellectual property rights"
   },
   {
    "t": "p",
    "x": "Without prejudice to any more specific provision of these Terms, any intellectual property rights, such as copyrights, trademark rights, patent rights and design rights related to this Website are the exclusive property of the Owner or its licensors and are subject to the protection granted by applicable laws or international treaties relating to intellectual property."
   },
   {
    "t": "p",
    "x": "All trademarks — nominal or figurative — and all other marks, trade names, service marks, word marks, illustrations, images, or logos appearing in connection with this Website are, and remain, the exclusive property of the Owner or its licensors and are subject to the protection granted by applicable laws or international treaties related to intellectual property."
   },
   {
    "t": "h2",
    "x": "Changes to these Terms"
   },
   {
    "t": "p",
    "x": "The Owner reserves the right to amend or otherwise modify these Terms at any time. In such cases, the Owner will appropriately inform the User of these changes."
   },
   {
    "t": "p",
    "x": "Such changes will only affect the relationship with the User for the future."
   },
   {
    "t": "p",
    "x": "The continued use of the Service will signify the User’s acceptance of the revised Terms. If Users do not wish to be bound by the changes, they must stop using the Service. Failure to accept the revised Terms, may entitle either party to terminate the Agreement."
   },
   {
    "t": "p",
    "x": "The applicable previous version will govern the relationship prior to the User’s acceptance. The User can obtain any previous version from the Owner."
   },
   {
    "t": "p",
    "x": "If required by applicable law, the Owner will specify the date by which the modified Terms will enter into force."
   },
   {
    "t": "h2",
    "x": "Assignment of contract"
   },
   {
    "t": "p",
    "x": "The Owner reserves the right to transfer, assign, dispose of by novation, or subcontract any or all rights or obligations under these Terms, taking the User’s legitimate interests into account. Provisions regarding changes of these Terms will apply accordingly."
   },
   {
    "t": "p",
    "x": "Users may not assign or transfer their rights or obligations under these Terms in any way, without the written permission of the Owner."
   },
   {
    "t": "h2",
    "x": "Contacts"
   },
   {
    "t": "p",
    "x": "All communications relating to the use of this Website must be sent using the contact information stated in this document."
   },
   {
    "t": "h2",
    "x": "Severability"
   },
   {
    "t": "p",
    "x": "Should any provision of these Terms be deemed or become invalid or unenforceable under applicable law, the invalidity or unenforceability of such provision shall not affect the validity of the remaining provisions, which shall remain in full force and effect."
   },
   {
    "t": "p",
    "x": "Any such invalid or unenforceable provision will be interpreted, construed and reformed to the extent reasonably required to render it valid, enforceable and consistent with its original intent. These Terms constitute the entire Agreement between Users and the Owner with respect to the subject matter hereof, and supersede all other communications, including but not limited to all prior agreements, between the parties with respect to such subject matter. These Terms will be enforced to the fullest extent permitted by law."
   },
   {
    "t": "h2",
    "x": "Governing law"
   },
   {
    "t": "p",
    "x": "These Terms are governed by the laws of the State of New York, without regard to conflict of laws principles."
   },
   {
    "t": "h2",
    "x": "Venue of jurisdiction"
   },
   {
    "t": "p",
    "x": "The exclusive competence to decide on any controversy resulting from or connected to these Terms lies with the state and federal courts located in New York County, New York."
   },
   {
    "t": "h2",
    "x": "Dispute resolution"
   },
   {
    "t": "h3",
    "x": "Amicable dispute resolution"
   },
   {
    "t": "p",
    "x": "Users may bring any disputes to the Owner who will try to resolve them amicably."
   },
   {
    "t": "p",
    "x": "While Users’ right to take legal action shall always remain unaffected, in the event of any controversy regarding the use of this Website or the Service, Users are kindly asked to contact the Owner at the contact details provided in this document."
   },
   {
    "t": "p",
    "x": "The User may submit the complaint including a brief description and, if applicable, the details of the related inquiry, to the Owner’s email address specified in this document."
   },
   {
    "t": "p",
    "x": "The Owner will process the complaint without undue delay and within 21 days of receiving it."
   }
  ]
 },
 "privacy": {
  "title": "Privacy Policy",
  "blocks": [
   {
    "t": "h1",
    "x": "Privacy Policy"
   },
   {
    "t": "p",
    "x": "Last updated: [date of publication]"
   },
   {
    "t": "p",
    "x": "This policy explains what information Credo Legal collects through its websites and landing pages, how we use it, who receives it and what choices you have. We collect the information you give us when you fill in a form, chat with us, call us or email us, and information that is collected automatically when you visit, including by advertising and analytics tools."
   },
   {
    "t": "p",
    "x": "This Website collects some Personal Data from its Users."
   },
   {
    "t": "p",
    "x": "This document contains a section dedicated to consumers and their privacy rights."
   },
   {
    "t": "p",
    "x": "This document can be printed for reference by using the print command in the settings of any browser."
   },
   {
    "t": "h2",
    "x": "Owner and Data Controller"
   },
   {
    "t": "p",
    "x": "Credo Legal – 1 Liberty Plaza, Suite 401, New York, NY 10006 [confirm legal entity name and address]"
   },
   {
    "t": "p",
    "x": "Mailing Address P.O. Box 105562, Atlanta, GA 30348-5562"
   },
   {
    "t": "p",
    "x": "Owner contact email: support@credolegal.com"
   },
   {
    "t": "h2",
    "x": "Types of Data collected"
   },
   {
    "t": "p",
    "x": "Among the types of Personal Data that this Website collects, by itself or through third parties, there are: first name; last name; phone number; email address; ZIP/Postal code; state; information about your debts and your situation that you choose to give us (the amount owed, the number, type and stage of your debts, whether a lawsuit or wage garnishment is involved, and anything you write in the form or the chat); Tracker; Usage Data; device information; browser information; unique device identifiers for advertising (Google Advertiser ID or IDFA, for example); advertising click identifiers and campaign information (for example gclid, gbraid, wbraid, fbclid and UTM parameters); Data communicated in order to use the Service."
   },
   {
    "t": "p",
    "x": "Complete details on each type of Personal Data collected are provided in the dedicated sections of this privacy policy or by specific explanation texts displayed prior to the Data collection."
   },
   {
    "t": "p",
    "x": "Personal Data may be freely provided by the User, or, in case of Usage Data, collected automatically when using this Website."
   },
   {
    "t": "p",
    "x": "Unless specified otherwise, all Data requested by this Website is mandatory and failure to provide this Data may make it impossible for this Website to provide its services. In cases where this Website specifically states that some Data is not mandatory, Users are free not to communicate this Data without consequences to the availability or the functioning of the Service."
   },
   {
    "t": "p",
    "x": "Users who are uncertain about which Personal Data is mandatory are welcome to contact the Owner."
   },
   {
    "t": "p",
    "x": "Any use of Cookies – or of other tracking tools – by this Website or by the owners of third-party services used by this Website serves the purpose of providing the Service required by the User, in addition to any other purposes described in the present document and in the Cookie Policy."
   },
   {
    "t": "p",
    "x": "Users are responsible for any third-party Personal Data obtained, published or shared through this Website and confirm that they have the third party’s consent to provide the Data to the Owner."
   },
   {
    "t": "h3",
    "x": "Information about your debts"
   },
   {
    "t": "p",
    "x": "The form asks about your debts so that an attorney can assess whether and how the firm can help. We use this information only to respond to your inquiry and, if you become a client, to represent you. We treat it as confidential. Please do not include account numbers, Social Security numbers or other identifiers that the form does not ask for."
   },
   {
    "t": "p",
    "x": "Some pages are about medical debt. If you tell us about medical bills, we treat that information with the same care. We do not ask for medical records or diagnoses through this Website."
   },
   {
    "t": "h2",
    "x": "Mode and place of processing the Data"
   },
   {
    "t": "h3",
    "x": "Methods of processing"
   },
   {
    "t": "p",
    "x": "The Owner takes appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data."
   },
   {
    "t": "p",
    "x": "The Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Owner, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of this Website (administration, sales, marketing, legal, system administration) or external parties (such as third-party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Owner at any time."
   },
   {
    "t": "h3",
    "x": "Place"
   },
   {
    "t": "p",
    "x": "The Data is processed in the United States, at the Owner’s operating offices and in any other places where the parties involved in the processing are located."
   },
   {
    "t": "h3",
    "x": "Retention time"
   },
   {
    "t": "p",
    "x": "Personal Data shall be processed and stored for as long as required by the purpose they have been collected for."
   },
   {
    "t": "p",
    "x": "Therefore:"
   },
   {
    "t": "li",
    "x": "Personal Data collected for purposes related to the performance of a contract between the Owner and the User shall be retained until such contract has been fully performed."
   },
   {
    "t": "li",
    "x": "Personal Data collected for the purposes of the Owner’s legitimate interests shall be retained as long as needed to fulfill such purposes. Users may find specific information regarding the legitimate interests pursued by the Owner within the relevant sections of this document or by contacting the Owner."
   },
   {
    "t": "li",
    "x": "Personal Data sent with an inquiry that does not lead to an engagement shall be retained for [period to be set by the firm] and then deleted, unless the law requires the Owner to keep it longer."
   },
   {
    "t": "p",
    "x": "The Owner may be allowed to retain Personal Data for a longer period whenever the User has given consent to such processing, as long as such consent is not withdrawn. Furthermore, the Owner may be obliged to retain Personal Data for a longer period whenever required to do so for the performance of a legal obligation or upon order of an authority."
   },
   {
    "t": "p",
    "x": "Once the retention period expires, Personal Data shall be deleted. Therefore, the right of access, the right to erasure, the right to rectification and the right to data portability cannot be enforced after expiration of the retention period."
   },
   {
    "t": "h2",
    "x": "The purposes of processing"
   },
   {
    "t": "p",
    "x": "The Data concerning the User is collected to allow the Owner to provide its Service, comply with its legal obligations, respond to enforcement requests, protect its rights and interests (or those of its Users or third parties), detect any malicious or fraudulent activity, as well as the following:"
   },
   {
    "t": "p",
    "x": "Analytics, Advertising, Remarketing and behavioral targeting, Session recording and heat mapping, Contacting the User, Live chat, Call tracking, Managing contacts and sending messages, User database management, Displaying content from external platforms, Hosting and infrastructure monitoring, Tag Management and Content performance and features testing (A/B testing)."
   },
   {
    "t": "p",
    "x": "For specific information about the Personal Data used for each purpose, the User may refer to the section “Detailed information on the processing of Personal Data”"
   },
   {
    "t": "h2",
    "x": "Detailed information on the processing of Personal Data"
   },
   {
    "t": "p",
    "x": "Personal Data is collected for the following purposes and using the following services:"
   },
   {
    "t": "li",
    "x": "Contact form: Formspree (Formspree, Inc.) receives what you enter in the form and passes it to the firm’s intake and client-management systems."
   },
   {
    "t": "li",
    "x": "Analytics: Google Analytics 4 (Google LLC) measures visits and the use of the form. The data is sent through a collection address operated for the firm before it reaches Google."
   },
   {
    "t": "li",
    "x": "Advertising and remarketing: Google Ads (Google LLC), Meta Pixel (Meta Platforms, Inc.) and Microsoft Advertising (Microsoft Corporation) record that a visit or an inquiry followed an advertisement and can show our advertisements to people who visited this Website."
   },
   {
    "t": "li",
    "x": "Session recording and heat mapping: Microsoft Clarity (Microsoft Corporation) and Mouseflow (Mouseflow ApS) record how visitors move through a page: clicks, scrolling and the pages viewed. What you type into form fields is masked and is not recorded."
   },
   {
    "t": "li",
    "x": "Live chat: Tidio (Tidio LLC) provides the chat window and stores the conversation."
   },
   {
    "t": "li",
    "x": "Call tracking: the phone number shown on a page can depend on the advertisement that brought you here, so that we know which advertisement led to a call. [Name of the call-tracking provider and whether calls are recorded: to be confirmed.]"
   },
   {
    "t": "li",
    "x": "Reviews and badges: the Trustpilot widget (Trustpilot A/S) and the Better Business Bureau seal are loaded from those organizations’ servers, which receive your IP address and browser information."
   },
   {
    "t": "li",
    "x": "Content testing: Optibase may show different versions of a page to different visitors to compare them."
   },
   {
    "t": "li",
    "x": "Tag management: Google Tag Manager (Google LLC) loads the analytics, advertising and recording tools listed here."
   },
   {
    "t": "li",
    "x": "Hosting: Webflow (Webflow, Inc.), with content delivery by Cloudflare and Fastly, hosts this Website and processes server logs, including IP addresses."
   },
   {
    "t": "p",
    "x": "The Cookie Policy lists the same services with links to their privacy information and ways to opt out."
   },
   {
    "t": "h2",
    "x": "Calls, text messages and email"
   },
   {
    "t": "p",
    "x": "If you give us your phone number or email address, we use them to respond to your inquiry and, if you become a client, to communicate about your matter. We send marketing calls or text messages made with automated technology only if you agreed to them where you gave us your number. You can reply STOP to a text message at any time. We do not sell or share phone numbers or text-message consent with third parties for their own marketing."
   },
   {
    "t": "h2",
    "x": "Advertising and your choices"
   },
   {
    "t": "p",
    "x": "We do not sell your Personal Data for money. The advertising and analytics services listed above receive online identifiers and information about your visits to this Website, and use them to measure and target advertising. Some state laws call this “sharing” or a “sale” of Personal Data, or “targeted advertising”."
   },
   {
    "t": "p",
    "x": "You can opt out by using the controls described in the Cookie Policy, or by contacting the Owner. [Whether this Website responds to the Global Privacy Control signal: to be confirmed.]"
   },
   {
    "t": "h2",
    "x": "Information on opting out of interest-based advertising"
   },
   {
    "t": "p",
    "x": "In addition to any opt-out feature provided by any of the services listed in this document, Users may learn more on how to generally opt out of interest-based advertising within the dedicated section of the Cookie Policy."
   },
   {
    "t": "h2",
    "x": "The rights of Users"
   },
   {
    "t": "p",
    "x": "Users may exercise certain rights regarding their Data processed by the Owner."
   },
   {
    "t": "p",
    "x": "Depending on the state where they live, Users may have the right to do the following:"
   },
   {
    "t": "li",
    "x": "Withdraw their consent at any time. Users have the right to withdraw consent where they have previously given their consent to the processing of their Personal Data."
   },
   {
    "t": "li",
    "x": "Opt out of targeted advertising and of the sale or sharing of their Data. Users have the right to ask the Owner not to use or disclose their Data for advertising based on their activity across websites. Further details are provided in the section “Advertising and your choices”."
   },
   {
    "t": "li",
    "x": "Access their Data. Users have the right to learn if Data is being processed by the Owner, obtain disclosure regarding certain aspects of the processing and obtain a copy of the Data being processed."
   },
   {
    "t": "li",
    "x": "Verify and seek rectification. Users have the right to verify the accuracy of their Data and ask for it to be updated or corrected."
   },
   {
    "t": "li",
    "x": "Have their Personal Data deleted or otherwise removed. Users have the right, under certain circumstances, to obtain the erasure of their Data from the Owner."
   },
   {
    "t": "li",
    "x": "Receive their Data and have it transferred to another controller. Users have the right to receive their Data in a structured, commonly used and machine readable format and, if technically feasible, to have it transmitted to another controller without any hindrance."
   },
   {
    "t": "li",
    "x": "Appeal and complain. If the Owner declines a request, Users may ask the Owner to reconsider, and may contact the attorney general of their state."
   },
   {
    "t": "li",
    "x": "Not be treated differently. The Owner will not deny services or offer different terms because a User exercised these rights."
   },
   {
    "t": "h3",
    "x": "How to exercise these rights"
   },
   {
    "t": "p",
    "x": "Any requests to exercise User rights can be directed to the Owner through the contact details provided in this document. These requests are free of charge and will be answered by the Owner as early as possible and within the time the applicable law allows (in most states, 45 days). The Owner may need to verify the User’s identity before acting on a request."
   },
   {
    "t": "h2",
    "x": "Cookie Policy"
   },
   {
    "t": "p",
    "x": "This Website uses Trackers. To learn more, the User may consult the Cookie Policy."
   },
   {
    "t": "h3",
    "x": "Legal action"
   },
   {
    "t": "p",
    "x": "The User’s Personal Data may be used for legal purposes by the Owner in Court or in the stages leading to possible legal action arising from improper use of this Website or the related Services."
   },
   {
    "t": "p",
    "x": "The User declares to be aware that the Owner may be required to reveal personal data upon request of public authorities."
   },
   {
    "t": "h3",
    "x": "Additional information about User’s Personal Data"
   },
   {
    "t": "p",
    "x": "In addition to the information contained in this privacy policy, this Website may provide the User with additional and contextual information concerning particular Services or the collection and processing of Personal Data upon request."
   },
   {
    "t": "h3",
    "x": "System logs and maintenance"
   },
   {
    "t": "p",
    "x": "For operation and maintenance purposes, this Website and any third-party services may collect files that record interaction with this Website (System logs) use other Personal Data (such as the IP Address) for this purpose."
   },
   {
    "t": "h3",
    "x": "Information not contained in this policy"
   },
   {
    "t": "p",
    "x": "More details concerning the collection or processing of Personal Data may be requested from the Owner at any time. Please see the contact information at the beginning of this document."
   },
   {
    "t": "h3",
    "x": "How “Do Not Track” requests are handled"
   },
   {
    "t": "p",
    "x": "This Website does not support “Do Not Track” requests. [Treatment of the Global Privacy Control signal: to be confirmed, see “Advertising and your choices”.]"
   },
   {
    "t": "p",
    "x": "To determine whether any of the third-party services it uses honor the “Do Not Track” requests, please read their privacy policies."
   },
   {
    "t": "h3",
    "x": "Changes to this privacy policy"
   },
   {
    "t": "p",
    "x": "The Owner reserves the right to make changes to this privacy policy at any time by notifying its Users on this page and possibly within this Website and/or – as far as technically and legally feasible – sending a notice to Users via any contact information available to the Owner. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom."
   },
   {
    "t": "p",
    "x": "Should the changes affect processing activities performed on the basis of the User’s consent, the Owner shall collect new consent from the User, where required."
   },
   {
    "t": "h2",
    "x": "Children"
   },
   {
    "t": "p",
    "x": "This Website is intended for adults. We do not knowingly collect Personal Data from anyone under 18. If you believe a minor has sent us information, contact the Owner and we will delete it."
   },
   {
    "t": "h2",
    "x": "No attorney-client relationship"
   },
   {
    "t": "p",
    "x": "Sending us information through this Website does not make you a client of the firm and does not create an attorney-client relationship. See the Terms of Use."
   },
   {
    "t": "h2",
    "x": "Personal Data (or Data)"
   },
   {
    "t": "p",
    "x": "Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person."
   },
   {
    "t": "h3",
    "x": "Usage Data"
   },
   {
    "t": "p",
    "x": "Information collected automatically through this Website (or third-party services employed in this Website), which can include: the IP addresses or domain names of the computers utilized by the Users who use this Website, the URI addresses (Uniform Resource Identifier), the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server’s answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Application) and the details about the path followed within the Application with special reference to the sequence of pages visited, and other parameters about the device operating system and/or the User’s IT environment."
   },
   {
    "t": "h3",
    "x": "User"
   },
   {
    "t": "p",
    "x": "The individual using this Website who, unless otherwise specified, coincides with the Data Subject."
   },
   {
    "t": "h3",
    "x": "Data Subject"
   },
   {
    "t": "p",
    "x": "The natural person to whom the Personal Data refers."
   },
   {
    "t": "h3",
    "x": "Data Processor (or Data Supervisor)"
   },
   {
    "t": "p",
    "x": "The natural or legal person, public authority, agency or other body which processes Personal Data on behalf of the Controller, as described in this privacy policy."
   },
   {
    "t": "h3",
    "x": "Data Controller (or Owner)"
   },
   {
    "t": "p",
    "x": "The natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of Personal Data, including the security measures concerning the operation and use of this Website. The Data Controller, unless otherwise specified, is the Owner of this Website."
   },
   {
    "t": "h3",
    "x": "This Website (or this Application)"
   },
   {
    "t": "p",
    "x": "The means by which the Personal Data of the User is collected and processed."
   },
   {
    "t": "h3",
    "x": "Service"
   },
   {
    "t": "p",
    "x": "The service provided by this Website as described in the relative terms (if available) and on this site/application."
   },
   {
    "t": "h3",
    "x": "Cookie"
   },
   {
    "t": "p",
    "x": "Cookies are Trackers consisting of small sets of data stored in the User’s browser."
   },
   {
    "t": "h3",
    "x": "Tracker"
   },
   {
    "t": "p",
    "x": "Tracker indicates any technology — e.g Cookies, unique identifiers, web beacons, embedded scripts, e-tags and fingerprinting — that enables the tracking of Users, for example by accessing or storing information on the User’s device."
   },
   {
    "t": "h2",
    "x": "Legal information"
   },
   {
    "t": "p",
    "x": "This privacy statement has been prepared to meet the United States federal and state privacy laws that apply to the Owner."
   },
   {
    "t": "p",
    "x": "This privacy policy relates solely to this Website, if not stated otherwise within this document."
   }
  ]
 },
 "cookie": {
  "title": "Cookie Policy",
  "blocks": [
   {
    "t": "h1",
    "x": "Cookie Policy"
   },
   {
    "t": "p",
    "x": "Last updated: [date of publication]"
   },
   {
    "t": "p",
    "x": "This document informs Users about the technologies that help this Website to achieve the purposes described below. Such technologies allow the Owner to access and store information (for example by using a Cookie) or use resources (for example by running a script) on a User’s device as they interact with this Website."
   },
   {
    "t": "p",
    "x": "For simplicity, all such technologies are defined as “Trackers” within this document – unless there is a reason to differentiate."
   },
   {
    "t": "p",
    "x": "Some of the purposes for which Trackers are used may also require the User’s consent. Whenever consent is given, it can be freely withdrawn at any time following the instructions provided in this document."
   },
   {
    "t": "p",
    "x": "This Website uses Trackers managed directly by the Owner (so-called “first-party” Trackers) and Trackers that enable services provided by a third party (so-called “third-party” Trackers). Unless otherwise specified within this document, third-party providers may access the Trackers managed by them."
   },
   {
    "t": "p",
    "x": "The validity and expiration periods of Cookies and other similar Trackers may vary depending on the lifetime set by the Owner or the relevant provider. Some of them expire upon termination of the User’s browsing session."
   },
   {
    "t": "p",
    "x": "In addition to what’s specified in the descriptions within each of the categories below, Users may find more precise and updated information regarding lifetime specification as well as any other relevant information – such as the presence of other Trackers – in the linked privacy policies of the respective third-party providers or by contacting the Owner."
   },
   {
    "t": "p",
    "x": "To find more information dedicated to consumers and their privacy rights, Users may read the privacy policy."
   },
   {
    "t": "h2",
    "x": "Activities strictly necessary for the operation of this Website and delivery of the Service"
   },
   {
    "t": "p",
    "x": "This Website uses so-called “technical” Cookies and other similar Trackers to carry out activities that are strictly necessary for the operation or delivery of the Service."
   },
   {
    "t": "h3",
    "x": "third-party Trackers"
   },
   {
    "t": "li",
    "x": "Hosting and security: Webflow (Webflow, Inc.), with content delivery by Cloudflare and Fastly, delivers the pages and may set Trackers that protect this Website from abuse. Personal Data processed: Tracker and Usage Data."
   },
   {
    "t": "li",
    "x": "Contact form: Formspree (Formspree, Inc.) receives the form when you send it. Personal Data processed: the Data you enter in the form."
   },
   {
    "t": "h2",
    "x": "Other activities involving the use of Trackers"
   },
   {
    "t": "p",
    "x": "Basic interactions & functionalities"
   },
   {
    "t": "p",
    "x": "This Website uses Trackers to enable basic interactions and functionalities, allowing Users to access selected features of the Service and facilitating the User’s communication with the Owner."
   },
   {
    "t": "li",
    "x": "Live chat: Tidio (Tidio LLC) provides the chat window and remembers your conversation. It loads after you first interact with a page. Personal Data processed: Tracker, Usage Data and what you write in the chat."
   },
   {
    "t": "li",
    "x": "Review and accreditation badges: the Trustpilot widget (Trustpilot A/S) and the Better Business Bureau seal are loaded from those organizations’ servers. Personal Data processed: Tracker and Usage Data."
   },
   {
    "t": "h3",
    "x": "Measurement"
   },
   {
    "t": "p",
    "x": "This Website uses Trackers to measure visits and to see which pages and advertisements lead to inquiries."
   },
   {
    "t": "li",
    "x": "Google Analytics 4 (Google LLC). Personal Data processed: Tracker and Usage Data. Opt out: Google Analytics opt-out browser add-on (tools.google.com/dlpage/gaoptout)."
   },
   {
    "t": "li",
    "x": "Campaign information stored by this Website itself. When you arrive from an advertisement, this Website stores the campaign parameters and click identifiers from the link (for example utm_source, gclid, fbclid) in your browser and attaches them to your inquiry, so that we know which advertisement it came from."
   },
   {
    "t": "h3",
    "x": "Session recording and heat mapping"
   },
   {
    "t": "p",
    "x": "This Website uses services that record how visitors use a page (clicks, scrolling and the pages viewed) so that we can find and fix problems. What you type into form fields is masked and is not recorded."
   },
   {
    "t": "li",
    "x": "Microsoft Clarity (Microsoft Corporation). Personal Data processed: Tracker and Usage Data."
   },
   {
    "t": "li",
    "x": "Mouseflow (Mouseflow ApS). Personal Data processed: Tracker and Usage Data. Opt out: mouseflow.com/opt-out."
   },
   {
    "t": "h3",
    "x": "Advertising and remarketing"
   },
   {
    "t": "p",
    "x": "This Website uses Trackers to record that a visit or an inquiry followed an advertisement and to show our advertisements to people who visited this Website."
   },
   {
    "t": "li",
    "x": "Google Ads conversion tracking and remarketing (Google LLC). Personal Data processed: Tracker and Usage Data. Opt out: Google Ads Settings (adssettings.google.com)."
   },
   {
    "t": "li",
    "x": "Meta Pixel (Meta Platforms, Inc.). Personal Data processed: Tracker and Usage Data. Opt out: Meta ad preferences (facebook.com/adpreferences)."
   },
   {
    "t": "li",
    "x": "Microsoft Advertising (Microsoft Corporation). Personal Data processed: Tracker and Usage Data. Opt out: Microsoft ad settings (account.microsoft.com/privacy/ad-settings)."
   },
   {
    "t": "h3",
    "x": "Content testing"
   },
   {
    "t": "li",
    "x": "Optibase. May show different versions of a page to different visitors to compare them. Personal Data processed: Tracker and Usage Data."
   },
   {
    "t": "h3",
    "x": "Tag management"
   },
   {
    "t": "li",
    "x": "Google Tag Manager (Google LLC) loads the measurement, recording and advertising services listed above. Personal Data processed: Tracker and Usage Data."
   },
   {
    "t": "h2",
    "x": "How to manage preferences and provide or withdraw consent"
   },
   {
    "t": "p",
    "x": "There are various ways to manage Tracker related preferences and to provide and withdraw consent, where relevant:"
   },
   {
    "t": "p",
    "x": "Users can manage preferences related to Trackers from directly within their own device settings, for example, by preventing the use or storage of Trackers."
   },
   {
    "t": "p",
    "x": "This Website does not currently display a cookie notice or a consent-preferences tool. [To be confirmed: whether one will be added.] Users can control Trackers with the browser settings and the opt-out links described in this document."
   },
   {
    "t": "p",
    "x": "It is also possible, via relevant browser or device features, to delete previously stored Trackers, including those used to remember the User’s initial consent."
   },
   {
    "t": "p",
    "x": "Other Trackers in the browser’s local memory may be cleared by deleting the browsing history."
   },
   {
    "t": "p",
    "x": "With regard to any third-party Trackers, Users can manage their preferences and withdraw their consent via the related opt-out link (where provided), by using the means indicated in the third party’s privacy policy, or by contacting the third party."
   },
   {
    "t": "h3",
    "x": "Locating Tracker Settings"
   },
   {
    "t": "p",
    "x": "Users can, for example, find information about how to manage Cookies in the most commonly used browsers at the following addresses:"
   },
   {
    "t": "li",
    "x": "Google Chrome"
   },
   {
    "t": "li",
    "x": "Mozilla Firefox"
   },
   {
    "t": "li",
    "x": "Apple Safari"
   },
   {
    "t": "li",
    "x": "Microsoft Edge"
   },
   {
    "t": "li",
    "x": "Brave"
   },
   {
    "t": "li",
    "x": "Opera"
   },
   {
    "t": "h3",
    "x": "How to opt out of interest-based advertising"
   },
   {
    "t": "p",
    "x": "Notwithstanding the above, Users may follow the instructions provided by the Network Advertising Initiative (optout.networkadvertising.org) and the Digital Advertising Alliance (optout.aboutads.info), or use the advertising settings of Google, Meta and Microsoft listed above. Such initiatives allow Users to select their tracking preferences for most of the advertising tools. The Owner thus recommends that Users make use of these resources in addition to the information provided in this document."
   },
   {
    "t": "h3",
    "x": "Consequences of denying consent"
   },
   {
    "t": "p",
    "x": "Users are free to decide whether or not to grant consent. However, please note that Trackers help this Website to provide a better experience and advanced functionalities to Users (in line with the purposes outlined in this document). Therefore, in the absence of the User’s consent, the Owner may be unable to provide related features."
   },
   {
    "t": "h2",
    "x": "Owner and Data Controller"
   },
   {
    "t": "p",
    "x": "Credo Legal"
   },
   {
    "t": "p",
    "x": "1 Liberty Plaza, Suite 401, New York, NY 10006 [confirm legal entity name and address]"
   },
   {
    "t": "p",
    "x": "Mailing Address P.O. Box 105562, Atlanta, GA 30348-5562"
   },
   {
    "t": "p",
    "x": "Owner contact email: support@credolegal.com"
   },
   {
    "t": "p",
    "x": "Since the use of third-party Trackers through this Website cannot be fully controlled by the Owner, any specific references to third-party Trackers are to be considered indicative. In order to obtain complete information, Users are kindly requested to consult the privacy policies of the respective third-party services listed in this document."
   },
   {
    "t": "p",
    "x": "Given the objective complexity surrounding tracking technologies, Users are encouraged to contact the Owner should they wish to receive any further information on the use of such technologies by this Website."
   },
   {
    "t": "h2",
    "x": "Definitions and legal references"
   },
   {
    "t": "h3",
    "x": "Personal Data (or Data)"
   },
   {
    "t": "p",
    "x": "Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person."
   },
   {
    "t": "h3",
    "x": "Usage Data"
   },
   {
    "t": "p",
    "x": "Information collected automatically through this Website (or third-party services employed in this Website), which can include: the IP addresses or domain names of the computers utilized by the Users who use this Website, the URI addresses (Uniform Resource Identifier), the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server’s answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Application) and the details about the path followed within the Application with special reference to the sequence of pages visited, and other parameters about the device operating system and/or the User’s IT environment."
   },
   {
    "t": "h3",
    "x": "User"
   },
   {
    "t": "p",
    "x": "The individual using this Website who, unless otherwise specified, coincides with the Data Subject."
   },
   {
    "t": "h3",
    "x": "Data Subject"
   },
   {
    "t": "p",
    "x": "The natural person to whom the Personal Data refers."
   },
   {
    "t": "h3",
    "x": "Data Processor (or Data Supervisor)"
   },
   {
    "t": "p",
    "x": "The natural or legal person, public authority, agency or other body which processes Personal Data on behalf of the Controller, as described in this privacy policy."
   },
   {
    "t": "h3",
    "x": "Data Controller (or Owner)"
   },
   {
    "t": "p",
    "x": "The natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of Personal Data, including the security measures concerning the operation and use of this Website. The Data Controller, unless otherwise specified, is the Owner of this Website."
   },
   {
    "t": "h3",
    "x": "This Website (or this Application)"
   },
   {
    "t": "p",
    "x": "The means by which the Personal Data of the User is collected and processed."
   },
   {
    "t": "h3",
    "x": "Service"
   },
   {
    "t": "p",
    "x": "The service provided by this Website as described in the relative terms (if available) and on this site/application."
   },
   {
    "t": "h3",
    "x": "Cookie"
   },
   {
    "t": "p",
    "x": "Cookies are Trackers consisting of small sets of data stored in the User’s browser."
   },
   {
    "t": "h3",
    "x": "Tracker"
   },
   {
    "t": "p",
    "x": "Tracker indicates any technology – e.g Cookies, unique identifiers, web beacons, embedded scripts, e-tags and fingerprinting – that enables the tracking of Users, for example by accessing or storing information on the User’s device."
   },
   {
    "t": "h3",
    "x": "Legal information"
   },
   {
    "t": "p",
    "x": "This privacy statement has been prepared to meet the United States federal and state privacy laws that apply to the Owner."
   },
   {
    "t": "p",
    "x": "This privacy policy relates solely to this Website, if not stated otherwise within this document."
   }
  ]
 }
};
