/* Generated by tools/website-start/build.mjs. Do not edit by hand. */
window.CREDO_SITE_DATA = {
 "clusterOrder": [
  "harassment",
  "lawsuit",
  "creditCard",
  "paydayLoan",
  "medicalDebt",
  "garnishment"
 ],
 "clusters": {
  "harassment": {
   "slug": "harassment",
   "label": "Collector harassment"
  },
  "lawsuit": {
   "slug": "lawsuit",
   "label": "Debt lawsuit"
  },
  "creditCard": {
   "slug": "credit-card",
   "label": "Credit card debt"
  },
  "paydayLoan": {
   "slug": "payday-loan",
   "label": "Payday loans"
  },
  "medicalDebt": {
   "slug": "medical-debt",
   "label": "Medical debt"
  },
  "garnishment": {
   "slug": "garnishment",
   "label": "Wage garnishment"
  }
 },
 "variantOrder": [
  "stop-calls",
  "fight-back",
  "respond-in-time",
  "demand-proof",
  "know-your-rights",
  "reduce-or-remove"
 ],
 "variants": {
  "stop-calls": {
   "slug": "stop-calls",
   "label": "Stop the Calls",
   "tagline": "Relief from collector harassment",
   "promise": "End the harassment. Stop the calls.",
   "home": "harassment",
   "homeH1": [
    "Stop the calls. ",
    "Today",
    "."
   ],
   "homeSub": "When debt collectors won't stop calling, our attorneys send the legal notice that ends it. Same-day cease letters, federal-law protection, attorneys licensed in your state.",
   "clusterLead": "Whatever kind of debt the calls are about, we can stop them.",
   "visitor": "Someone whose phone won't stop ringing: collectors before 8 AM, threats of arrest, calls to family or work. They want the calls to stop now.",
   "services": {
    "harassment": {
     "file": "stop-calls",
     "slot": "harassment-var-a-stop-calls",
     "fit": "perfect",
     "note": "",
     "h1": "Debt Collectors Won't Stop Calling?",
     "lede": "Our Attorneys Can Make Them Stop."
    },
    "lawsuit": {
     "file": "lawsuit-summons",
     "slot": "lawsuit-served-papers-var-a-act-now",
     "fit": "best",
     "note": "Lawsuit equivalent of \"stop the calls\": act-now framing on a fresh summons.",
     "h1": "You've Been Served Papers?",
     "lede": "Our Attorneys Can Help You Respond On Time."
    },
    "creditCard": {
     "file": "cc-stop-calls",
     "slot": "cc-harassment-var-a-stop-calls-dyn",
     "fit": "perfect",
     "note": "",
     "h1": "Credit Card Debt Collector Calling You?",
     "lede": "Our Attorneys Can Help Make Them Stop."
    },
    "paydayLoan": {
     "file": "payday-harassment",
     "slot": "payday-loan-harassment-var-a-stop-calls-dyn",
     "fit": "perfect",
     "note": "",
     "h1": "Payday Lenders Calling Aggressively?",
     "lede": "Our Attorneys Can Help Make Them Stop."
    },
    "medicalDebt": {
     "file": "med-attorney",
     "slot": "med-debt-harassment-var-a-stop-calls",
     "fit": "perfect",
     "note": "",
     "h1": "Struggling With Medical Debt?",
     "lede": "Our Attorneys Can Help You Fight Harassment & Challenge Debt."
    },
    "garnishment": {
     "file": "garn-how-to-stop",
     "slot": "all-states-garn-var-a-fight",
     "fit": "best",
     "note": "Garnishment equivalent of \"stop\": fight the garnishment.",
     "h1": "How to Stop a Wage Garnishment",
     "lede": "Our Attorneys Can Help Cut It or End It, Even After It Starts."
    }
   }
  },
  "fight-back": {
   "slug": "fight-back",
   "label": "Fight Back",
   "tagline": "Pursue damages, hold them accountable",
   "promise": "They broke the law. We help you sue them.",
   "home": "harassment",
   "homeH1": [
    "Fight back. They ",
    "broke the law",
    "."
   ],
   "homeSub": "FDCPA violations carry $1,000 per lawsuit. Garnishments can be reduced. Payday loans can be voided. Our attorneys turn what was done to you into a case against them.",
   "clusterLead": "Whatever the violation, we build the claim.",
   "visitor": "Someone done waiting it out: wants to know what they can recover, who they can sue, and what the law gives them as leverage.",
   "services": {
    "harassment": {
     "file": "attorney",
     "slot": "harassment-fdcpa-var-b-we-sue-them",
     "fit": "perfect",
     "note": "",
     "h1": "Need a Consumer Debt Attorney?",
     "lede": "We Explain Your Rights Against Debt Harassment under FDCPA for Free."
    },
    "lawsuit": {
     "file": "lawsuit-fight-back",
     "slot": "lawsuit-defense-var-a-fight-back",
     "fit": "perfect",
     "note": "",
     "h1": "Is a Creditor Suing You?",
     "lede": "Our Attorneys Can Help You Challenge Their Claims."
    },
    "creditCard": {
     "file": "cc-violations",
     "slot": "cc-harassment-var-b-violations-dyn",
     "fit": "perfect",
     "note": "",
     "h1": "Credit Card Debt Collectors After You?",
     "lede": "Our Attorneys Can Help Make Them Pay."
    },
    "paydayLoan": {
     "file": "payday-fight-back",
     "slot": "payday-loan-rights-var-b-fight-back",
     "fit": "perfect",
     "note": "",
     "h1": "Payday Loan Broke the Law?",
     "lede": "Our Attorneys Can Check Legality and Build Your Case."
    },
    "medicalDebt": {
     "file": "med-bills-errors",
     "slot": "med-debt-harassment-var-b-invalid-bills",
     "fit": "best",
     "note": "Medical equivalent: challenge the bills.",
     "h1": "Medical Bills Look Wrong?",
     "lede": "Our Attorneys Can Help You Challenge Their Claims."
    },
    "garnishment": {
     "file": "garn-attorney",
     "slot": "post-judgment-garn-var-a-fight-active",
     "fit": "perfect",
     "note": "",
     "h1": "Is Your Paycheck Being Garnished?",
     "lede": "Our Attorneys Can Challenge Their Claims and Fight for Your Paycheck."
    }
   }
  },
  "respond-in-time": {
   "slug": "respond-in-time",
   "label": "Respond in Time",
   "tagline": "Deadline urgency: don't miss the window",
   "promise": "Don't miss the deadline. Respond on time.",
   "home": "lawsuit",
   "homeH1": [
    "You have a deadline. We help you ",
    "meet it",
    "."
   ],
   "homeSub": "Default judgment, wage garnishment, repossession: all start when a deadline passes. Our attorneys file the response, examine the claim, and protect what's yours.",
   "clusterLead": "Whatever started the clock, we beat it.",
   "visitor": "Someone holding a summons or notice with a date on it. They need to act before something irreversible happens.",
   "services": {
    "harassment": {
     "file": "act-fast",
     "slot": "all-states-fdcpa-var-b-action-fast",
     "fit": "best",
     "note": "Harassment equivalent: act fast on the FDCPA timeline.",
     "h1": "Let's See If We Can Help You with Creditor Harassment and Debt",
     "lede": "Fill in the short form below to see if you qualify."
    },
    "lawsuit": {
     "file": "lawsuit-respond",
     "slot": "lawsuit-collection-var-a-urgency",
     "fit": "perfect",
     "note": "Account champion.",
     "h1": "Debt Collector Suing You?",
     "lede": "Our Attorneys Can Help You Respond On Time."
    },
    "creditCard": {
     "file": "cc-lawsuit-respond",
     "slot": "cc-lawsuit-var-a-urgency",
     "fit": "perfect",
     "note": "",
     "h1": "Sued for Credit Card Debt?",
     "lede": "Our Attorneys Can Help You Respond On Time."
    },
    "paydayLoan": {
     "file": "payday-lawsuit-respond",
     "slot": "payday-loan-lawsuit-var-a-urgency",
     "fit": "perfect",
     "note": "",
     "h1": "Payday Lender Suing You?",
     "lede": "Our Attorneys Can Help You Act On Time."
    },
    "medicalDebt": {
     "file": "med-lawsuit-respond",
     "slot": "med-debt-lawsuit-var-a-urgency",
     "fit": "perfect",
     "note": "",
     "h1": "Medical Debt Collector Suing You?",
     "lede": "Our Attorneys Can Help You Respond On Time."
    },
    "garnishment": {
     "file": "garn-prevention",
     "slot": "pre-judgment-garn-var-a-prevention",
     "fit": "best",
     "note": "Garnishment equivalent: prevent garnishment before judgment.",
     "h1": "Garnishment Looming?",
     "lede": "Our Attorneys Can Help You Stop It Before It Starts."
    }
   }
  },
  "demand-proof": {
   "slug": "demand-proof",
   "label": "Demand Proof",
   "tagline": "Make them prove the debt",
   "promise": "Don't pay debt they can't prove.",
   "home": "lawsuit",
   "homeH1": [
    "Make them ",
    "prove it",
    ". Or it goes away."
   ],
   "homeSub": "Debt collectors and original creditors must legally prove what they claim: ownership, amount, accuracy. When they can't, the case can be dismissed and the debt can come off your credit report.",
   "clusterLead": "Whatever they claim, we test it.",
   "visitor": "Someone who suspects the debt isn't legitimate: wrong amount, doesn't recognize it, sold between collectors. They want to challenge before paying.",
   "services": {
    "harassment": {
     "file": "violations",
     "slot": "harassment-var-b-violations",
     "fit": "best",
     "note": "Harassment equivalent: evidence of each violation.",
     "h1": "Debt Collectors Won't Stop Calling?",
     "lede": "Our Attorneys Can Make Them Pay."
    },
    "lawsuit": {
     "file": "lawsuit-proof",
     "slot": "lawsuit-collection-var-b-proof-challenge",
     "fit": "perfect",
     "note": "",
     "h1": "Debt Collector Suing You?",
     "lede": "Our Attorneys Can Help You Challenge Their Claims."
    },
    "creditCard": {
     "file": "cc-lawsuit-records",
     "slot": "cc-lawsuit-var-b-proof-challenge",
     "fit": "perfect",
     "note": "",
     "h1": "Sued for Credit Card Debt?",
     "lede": "Our Attorneys Find Errors and Challenge Their Claims."
    },
    "paydayLoan": {
     "file": "payday-lawsuit-proof",
     "slot": "payday-loan-lawsuit-var-b-proof-challenge",
     "fit": "perfect",
     "note": "",
     "h1": "Payday Loan Debt Seems Wrong?",
     "lede": "Our Attorneys Can Help You Dispute It."
    },
    "medicalDebt": {
     "file": "med-bills-errors",
     "slot": "med-debt-lawsuit-var-b-billing-errors",
     "fit": "perfect",
     "note": "",
     "h1": "Medical Bills Look Wrong?",
     "lede": "Our Attorneys Can Help You Challenge Their Claims."
    },
    "garnishment": {
     "file": "garn-attorney",
     "slot": "post-judgment-garn-var-a-fight-active",
     "fit": "best",
     "note": "Garnishment equivalent: challenge the underlying judgment.",
     "h1": "Is Your Paycheck Being Garnished?",
     "lede": "Our Attorneys Can Challenge Their Claims and Fight for Your Paycheck."
    }
   }
  },
  "know-your-rights": {
   "slug": "know-your-rights",
   "label": "Know Your Rights",
   "tagline": "Plain-English legal education",
   "promise": "Know what the law gives you. Before you do anything.",
   "home": "harassment",
   "homeH1": [
    "You have ",
    "more rights",
    " than you think."
   ],
   "homeSub": "FDCPA. FCRA. CFPB rules. State licensing law. Federal garnishment caps. Our attorneys explain what applies to your situation, at no cost, so you can decide from a position of knowledge.",
   "clusterLead": "Whatever your situation, we explain where you stand.",
   "visitor": "Someone in the research phase. Not panicked yet. Wants to understand the law before deciding whether to pay, dispute, settle, or ignore.",
   "services": {
    "harassment": {
     "file": "rights-verbatim",
     "slot": "harassment-fdcpa-var-a-education",
     "fit": "perfect",
     "note": "Account champion for the harassment angle.",
     "h1": "Our Attorneys Can Explain Your Rights and Act.",
     "lede": "Our Attorneys Can Make Them Pay."
    },
    "lawsuit": {
     "file": "lawsuit-attorney",
     "slot": "lawsuit-defense-var-b-level-field",
     "fit": "best",
     "note": "Lawsuit equivalent: how an attorney levels the field.",
     "h1": "Is a Creditor Suing You?",
     "lede": "Our Attorneys Can Help You Level the Playing Field."
    },
    "creditCard": {
     "file": "cc-negotiation",
     "slot": "cc-negotiation-var-a-negotiate",
     "fit": "best",
     "note": "Credit card equivalent: negotiation and validation options.",
     "h1": "Got Credit Card Debt?",
     "lede": "Our Attorneys Can Help You Negotiate."
    },
    "paydayLoan": {
     "file": "payday-rights",
     "slot": "payday-loan-rights-var-a-education",
     "fit": "perfect",
     "note": "",
     "h1": "Confused About Payday Loan Rights?",
     "lede": "Our Attorneys Can Help You Understand Them and Act."
    },
    "medicalDebt": {
     "file": "med-fdcpa-rights",
     "slot": "med-debt-rights-var-a-education",
     "fit": "perfect",
     "note": "",
     "h1": "Confused About Your Medical Debt?",
     "lede": "Our Attorneys Can Help You Know Your Rights and Act."
    },
    "garnishment": {
     "file": "garn-prevention",
     "slot": "pre-judgment-garn-var-b-rights",
     "fit": "perfect",
     "note": "",
     "h1": "Garnishment Looming?",
     "lede": "Our Attorneys Can Help You Stop It Before It Starts."
    }
   }
  },
  "reduce-or-remove": {
   "slug": "reduce-or-remove",
   "label": "Reduce or Remove",
   "tagline": "Outcome-focused: settle, exempt, remove",
   "promise": "Reduce what you owe. Remove what you don't.",
   "home": "creditCard",
   "homeH1": [
    "You may owe ",
    "less than they say",
    ". Or nothing at all."
   ],
   "homeSub": "Negotiated settlements. Garnishment exemptions. Credit-report removals. FDCPA recoveries. Our attorneys pursue every avenue to reduce what's claimed and clear what shouldn't be there.",
   "clusterLead": "Whatever the balance, we work it down.",
   "visitor": "Someone past the urgent phase and past the \"is this legit?\" question. They want to reduce the number: settle, exempt, remove, recover.",
   "services": {
    "harassment": {
     "file": "more-money",
     "slot": "harassment-multiple-collectors-var-b-aggregation",
     "fit": "best",
     "note": "Harassment equivalent: combined damages from multiple collectors.",
     "h1": "Multiple Debt Collectors Harassing You?",
     "lede": "Our Attorneys Can Help Make Them Pay."
    },
    "lawsuit": {
     "file": "lawsuit-options",
     "slot": "lawsuit-served-papers-var-b-reassurance",
     "fit": "best",
     "note": "Lawsuit equivalent: \"know your options\" outcome framing.",
     "h1": "Received a Lawsuit Summons?",
     "lede": "Our Attorneys Can Help You Make Sense of It and Act."
    },
    "creditCard": {
     "file": "cc-negotiation",
     "slot": "cc-negotiation-var-a-negotiate",
     "fit": "perfect",
     "note": "Credit card champion.",
     "h1": "Got Credit Card Debt?",
     "lede": "Our Attorneys Can Help You Negotiate."
    },
    "paydayLoan": {
     "file": "payday-violations",
     "slot": "payday-loan-harassment-var-b-violations-dyn",
     "fit": "best",
     "note": "Payday equivalent: recovery for violations.",
     "h1": "Payday Lenders Violating Your Rights?",
     "lede": "Our Attorneys Can Help Make Them Pay."
    },
    "medicalDebt": {
     "file": "med-credit-report",
     "slot": "med-debt-rights-var-b-credit-report",
     "fit": "perfect",
     "note": "",
     "h1": "Chased for Medical Debt You Don't Recognize?",
     "lede": "Make them prove it — our attorneys challenge whether you owe the debt at all, and how much."
    },
    "garnishment": {
     "file": "garn-exemptions",
     "slot": "post-judgment-garn-var-b-exemptions",
     "fit": "perfect",
     "note": "",
     "h1": "Paycheck Already Garnished?",
     "lede": "You May Qualify for Exemptions. Our Attorneys Can Help."
    }
   }
  }
 }
};
